### ISSUE TITLE
I am seeing a weird virus 

### ISSUE THREAD

**Issue by rashwell** [raylib-extras/raylib-quickstart#12]
![Screenshot 2024-11-24 224654](https://github.com/user-attachments/assets/e5e0901a-7b24-4422-adfd-ac927bb0aafb)

**Comment by JeffM2501** [comment]
yes, that is a false positive on the premake5.exe because it is unsigned, some overly aggressive systems flag several raylib things as viruses when they are not.
You can always get your own premake5.exe from the premake site.
https://premake.github.io/
