### ISSUE TITLE
Template not working?

### ISSUE THREAD

**Issue by Krater107a** [raylib-extras/raylib-quickstart#14]
Windows 11 24h2, VSCode + c/c++ extension, gcc (x86_64-win32-seh-rev0, Built by MinGW-Builds project) 14.2.0 (this was already installed on my system) (I can build and run simple example c/cpp projects with this setup.)

* Cloned repo with git clone https://github.com/raylib-extras/raylib-quickstart.git
* copied repo to new folder renamed to "testproj5"
* opened folder in VSCode
* pressed f5
----following error occurred: (output is from VSCode terminal)----

*  Executing task: D:\root\projects\raylib\testproj5\build\premake5.exe gmake2 

calling externals
Raylib not found, downloading from github
Unzipping to D:/root/projects/raylib/testproj5/build/external
Building configurations...
Running action 'gmake2'...
Generated ../Makefile...
Generated build_files/testproj5.make...
Generated build_files/raylib.make...
Done (3870ms).
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: D:\root\mingw64\bin\mingw32-make.exe SHELL=cmd 

"==== Building raylib (debug_x64) ===="
Creating obj/x64/Debug/raylib
"raudio.c"
process_begin: CreateProcess(NULL, cc -MD -MP -DDEBUG -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -I../external/raylib-master/src -I../external/raylib-master/src/external/glfw/include -m64 -g -o obj/x64/Debug/raylib/raudio.o -MF obj/x64/Debug/raylib/raudio.d -c ../external/raylib-master/src/raudio.c, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make[1]: *** [raylib.make:237: obj/x64/Debug/raylib/raudio.o] Error 2     
mingw32-make: *** [Makefile:78: raylib] Error 2

 *  The terminal process "D:\root\mingw64\bin\mingw32-make.exe 'SHELL=cmd'" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it. 

----Additional Information (This is NOT part of the above error message)----
-- Hidden folder build\build_files\obj\x64 is empty.
-- Folder build\external\raylib-master\src does contain file raudio.c

**Comment by JeffM2501** [comment]
what version of MinGW-W64 do you have?
run
```
gcc --version
```

**Comment by Krater107a** [comment]
gcc (x86_64-win32-seh-rev0, Built by MinGW-Builds project) 14.2.0
Copyright (C) 2024 Free Software Foundation, Inc.

**Comment by JeffM2501** [comment]
That should be fine, was it able to create the raylib sources in external/raylib-master/src ?

**Comment by Krater107a** [comment]
I am damn new to c/c++ so will do my best to answer.

>> was it able to create the raylib sources in external/raylib-master/src ?

yes? there's a lot of stuff in there, 2 folders, a bunch of .c and .h files along with others.

**Comment by JeffM2501** [comment]
then all I can think of is that your mingw is missing something, the error doesn't say what file it can't find.

I'm not sure how you got your mingw, but we recommend the W64Devkit https://github.com/skeeto/w64devkit/releases

**Comment by Krater107a** [comment]
Thank you for your help in this matter, I will try a new mingw.

**Comment by Krater107a** [comment]
Ok, have tried "W64Devkit" as recommended:
* unpacked w64devkit
* modified w64devkit configuration file to point to the appropriate projects folder
* made a fresh duplicate of "raylib-quickstart" template
* ran w64devkit.exe to get a shell
* navigated to my new project
* typed in code . to open new project folder in VSCode.
* pressed f5 to build project

----VSCode terminal output----
 *  Executing task: D:\root\projects\raylib\testproj6\build\premake5.exe gmake2 

calling externals
Raylib not found, downloading from github
Unzipping to D:/root/projects/raylib/testproj6/build/external
Building configurations...
Running action 'gmake2'...
Generated ../Makefile...
Generated build_files/testproj6.make...
Generated build_files/raylib.make...
Done (3740ms).
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: D:\root\w64devkit\bin\mingw32-make.exe SHELL=cmd 

"==== Building raylib (debug_x64) ===="
Creating obj/x64/Debug/raylib
The syntax of the command is incorrect.
make[1]: *** [raylib.make:195: obj/x64/Debug/raylib] Error 1
make: *** [Makefile:78: raylib] Error 2

 *  The terminal process "D:\root\w64devkit\bin\mingw32-make.exe 'SHELL=cmd'" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by JeffM2501** [comment]
Did you add the bin dir of that new mingw to your path?

**Comment by Krater107a** [comment]
> Did you add the bin dir of that new mingw to your path?

No, i didn't.

----From w64devkit git repo:---
> Inside is w64devkit.exe, which launches a console window with the environment configured and ready to go. It is the easiest way to enter the development environment, and requires no system changes.
---- ----

There's like 200+ .exe's in that bin folder I am concerned that there will be cmds that get conflicted with the normal windows cmds?

**Comment by JeffM2501** [comment]
no, they will not. You need that entire thing in your path.
also make sure that you don't have any other GCCs or mingws in your path.

**Comment by Krater107a** [comment]
Ok added w64devkit\bin to my machine's path variable and success! Worked on the first try! Thank you very much for your time and patience.

I will close this issue.
