### ISSUE TITLE
FYI : Mac and permission...

### ISSUE THREAD

**Issue by rcarlier** [raylib-extras/raylib-quickstart#15]
On my mac (Apple M3, 15.1.1) , the file `premake5.osx` will refuse to run if you don't set the permissions...

1. Element `premake5.osx` not open : click on (?) top right
2. bla bla bla... click on "Privacy and security" (on settings)
3. search "security"
4. you see `premake5.osx` somewhere around there, and need to click on "allow anyway"

![perm1](https://github.com/user-attachments/assets/78b3eb60-405a-4d07-bbbd-e52afab9af82)

![perm2](https://github.com/user-attachments/assets/e4730b8f-5ae9-4399-b59b-0bf7fc893daf)

**Comment by JeffM2501** [comment]
Yes, apple wants all aps to be signed by the mac store, and warns for any that are not. That's just a feature of your OS that you have to deal with. This is not anything that this project can change.

**Comment by rcarlier** [comment]
I know
It’s for helping other user - I have lost some time to find that :-)
