### ISSUE TITLE
it goes wrong in main.c (debian12 lxde)

### ISSUE THREAD

**Issue by liaojiaao** [raylib-extras/raylib-quickstart#6]
when i change the main.c
only change DrawText("Hello Rayli") mines a "b" .
and after make ,run the app ,it dont show the texture (the pic)
![isuu](https://github.com/user-attachments/assets/a59fe26f-ecc9-4f5e-af0e-da9d1999fb96)

**Comment by JeffM2501** [comment]
how did you change the main.c?

**Comment by liaojiaao** [comment]
use nano .  when i changed , i can make .till i run it ,just like this...

**Comment by liaojiaao** [comment]
> how did you change the main.c?



> how did you change the main.c?

use nano .  when i changed , i can make .till i run it ,just like this...

**Comment by liaojiaao** [comment]
![isuu](https://github.com/user-attachments/assets/8e61c382-bd79-4b56-a5c2-dd814fbf94f5)
now its ok.
i dont know how it happen

**Comment by liaojiaao** [comment]
i change again , it happen again.
![isuu](https://github.com/user-attachments/assets/c0157817-ee35-402c-96d1-95671fab4750)

**Comment by liaojiaao** [comment]
i found this problem in this case is normal.
when i shut down the virtualbox (debian12 lxde).and start it . the last make is ok .
when i change it ,and make again , it goes wrong.
Maybe it is my debian's problem

**Comment by JeffM2501** [comment]
That looks like video driver issues.
Virtual machine video drivers with hardware accelerated 3d graphics can be tricky.
It may be easier to simply build on your host OS, not in a virtual machine.
But none of this is an issue with the quickstart.
